apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-demo-deployment
  namespace: local
  labels:
    app: k8-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-demo
  template:
    metadata:
      labels:
        app: k8-demo
    spec:
      containers:
      - name: k8-demo
        image: k8-demo:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000