apiVersion: v1
kind: Service
metadata:
  name: k8-demo-service
  namespace: demo
spec:
  type: NodePort
  selector:
    app: k8-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 32001